### ISSUE TITLE
Negative quantities allowed in POS quantity selector. 

### ISSUE THREAD

**Issue by Aquietkid** [Aquietkid/Bookstore-automation-system#12]
Though the quantity can not be reduced below 1 using the buttons, a negative value can be typed.

**Comment by Aquietkid** [comment]
The HTML part does specify a min value of 1, but typing negative values allows them to be used in the code.

**Comment by M-Waleed-SE** [comment]
> The HTML part does specify a min value of 1, but typing negative values allows them to be used in the code.

I have rechecked this, you can add negative value however that will  be caught on frontend
